// JavaScript Document
$(document).ready(function() {
	 // ambos procesaran en save.php
	 // servira para editar los de tipo input text.
$('.text').editable('save.php');
	 // servira para editar el cuadro combinado de paises
 $('.select').editable('save.php', { 
data   : " {'1':'BAYER DE COLOMBIA','2':'AHROBINS INTERN','3':'ABBOTT DE COLOMBIA','4':'ALCON DE COLOMBIA SA','5':'ALLERGAN','6':'AMERICA','7':'ANGLOPHARMA','8':'ARBOLEDA Y ARBOLEDA','9':'ARMOFAR','10':'ARTIBEL SILUETA','11':'ASEPTIC LTDA','12':'AVENTIS','13':'BAGO DE COLOMBIA','14':'BAXTER','15':'BAYER','16':'BAYER DE COLOMBIA','17':'BAYER OTC','18':'BEIERSDORF SA','19':'BEST','20':'BIOCHEM','21':'BIOGEN','22':'BIOLINE','23':'BOEHRINGER INGELHEIM','24':'BIOQUIFAR','25':'BREMYN','26':'BREMYMG','27':'BRISTOL FARMACEUTICA','28':'BUSSIE','29':'C,P, FARMACEUTICA LTDA','30':'CALIFORNIA','31':'CARIBE','32':'CERO S,A','33':'CHALVER','34':'CODISA','35':'COLGATE PALMOLIVE','36':'COLMED S,A','37':'CORBETA','38':'CONTEXPORT-FILIAL ABBOTT','39':'DERMACARE S,A','40':'DISMAPRIM','41':'DISTRICHAR'}",
type   : 'select',
submit : 'OK'
});
	 // servira para editar el textarea.
$('.textarea').editable('save.php', { 
type     : 'textarea',
submit   : 'OK'
});	 
 });
/*
$('.select').editable('save.php', { 
data   : " {'1':'BAYER DE COLOMBIA','2':'AH.ROBINS INTERN','3':'ABBOTT DE COLOMBIA', '4':'ALCON DE COLOMBIA S,A', 5':'ALLERGAN',
'6':'AMERICA','7':'ANGLOPHARMA', '8':'ARBOLEDA Y ARBOLEDA','9':'ARMOFAR','10':'ARTIBEL SILUETA','11':'ASEPTIC LTDA','12':'AVENTIS'
,'13':'BAGO DE COLOMBIA','14':'BAXTER','15':'BAYER','16':'BAYER DE COLOMBIA','17':'BAYER OTC','18':'BEIERSDORF S,A','19':'BEST'
,'20':'BIOCHEM','21':'BIOGEN','22':'BIOLINE','23':'BOEHRINGER INGELHEIM','24':'BIOQUIFAR','25':'BREMYN','26':'BREMYMG'
,'27':'BRISTOL FARMACEUTICA','28':'BUSSIE','29':'C,P, FARMACEUTICA LTDA','30':'CALIFORNIA','31':'CARIBE','32':'CERO S,A','33':'CHALVER'
,'34':'CODISA','35':'COLGATE PALMOLIVE','36':'COLMED S,A','37':'CORBETA','38':'CONTEXPORT-FILIAL ABBOTT','39':'DERMACARE S,A','40':'DISMAPRIM'
,'41':'DIST,RICHAR','42':'ANGLOPHARMA','43':'ANGLOPHARMA','44':'ANGLOPHARMA','45':'ANGLOPHARMA','46':'ANGLOPHARMA','47':'ANGLOPHARMA'
,'48':'ANGLOPHARMA','49':'ANGLOPHARMA','50':'ANGLOPHARMA','51':'ANGLOPHARMA','52':'ANGLOPHARMA','53':'ANGLOPHARMA','54':'ANGLOPHARMA'
,'55':'ANGLOPHARMA','56':'ANGLOPHARMA','57':'ANGLOPHARMA','58':'ANGLOPHARMA','59':'ANGLOPHARMA','60':'ANGLOPHARMA','61':'ANGLOPHARMA'
,'62':'ANGLOPHARMA','63':'ANGLOPHARMA','64':'ANGLOPHARMA','65':'ANGLOPHARMA','66':'ANGLOPHARMA','67':'ANGLOPHARMA','68':'ANGLOPHARMA'
,'69':'ANGLOPHARMA','70':'ANGLOPHARMA','71':'ANGLOPHARMA','72':'ANGLOPHARMA','73':'ANGLOPHARMA','74':'ANGLOPHARMA','75':'ANGLOPHARMA'
,'76':'ANGLOPHARMA','77':'ANGLOPHARMA','78':'ANGLOPHARMA','79':'ANGLOPHARMA','80':'ANGLOPHARMA','81':'ANGLOPHARMA','82':'ANGLOPHARMA'
,'83':'ANGLOPHARMA','84':'ANGLOPHARMA','85':'ANGLOPHARMA','86':'ANGLOPHARMA','87':'ANGLOPHARMA','88':'ANGLOPHARMA','89':'ANGLOPHARMA'
,'90':'ANGLOPHARMA','91':'ANGLOPHARMA','92':'ANGLOPHARMA','93':'ANGLOPHARMA','94':'ANGLOPHARMA','95':'ANGLOPHARMA','96':'ANGLOPHARMA'
,'97':'ANGLOPHARMA','98':'ANGLOPHARMA','100':'ANGLOPHARMA','101':'ANGLOPHARMA','102':'ANGLOPHARMA','103':'ANGLOPHARMA','104':'ANGLOPHARMA'
,'105':'ANGLOPHARMA','106':'ANGLOPHARMA','107':'ANGLOPHARMA','108':'ANGLOPHARMA','109':'ANGLOPHARMA','110':'ANGLOPHARMA','111':'ANGLOPHARMA'
,'112':'ANGLOPHARMA','113':'ANGLOPHARMA','114':'ANGLOPHARMA','115':'ANGLOPHARMA','116':'ANGLOPHARMA','117':'ANGLOPHARMA','118':'ANGLOPHARMA'
,'119':'ANGLOPHARMA','120':'ANGLOPHARMA','121':'ANGLOPHARMA','122':'ANGLOPHARMA','123':'ANGLOPHARMA','124':'ANGLOPHARMA','125':'ANGLOPHARMA'
,'126':'ANGLOPHARMA','127':'ANGLOPHARMA','128':'ANGLOPHARMA','129':'ANGLOPHARMA','130':'ANGLOPHARMA','131':'ANGLOPHARMA','132':'ANGLOPHARMA'
,'133':'ANGLOPHARMA','134':'ANGLOPHARMA','135':'ANGLOPHARMA','136':'ANGLOPHARMA','137':'ANGLOPHARMA','138':'ANGLOPHARMA','139':'ANGLOPHARMA'
,'140':'ANGLOPHARMA','141':'ANGLOPHARMA','142':'ANGLOPHARMA'}",
type   : 'select',
submit : 'OK'
});
*/